# Generated by Django 5.0.6 on 2024-08-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_NO', models.DecimalField(decimal_places=1, max_digits=10)),
                ('MONTHS', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='page2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_NO', models.DecimalField(decimal_places=1, max_digits=10)),
                ('MONTHS', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='page3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_NO', models.DecimalField(decimal_places=1, max_digits=10)),
                ('MONTHS', models.CharField(max_length=50)),
            ],
        ),
    ]
