# Generated by Django 5.0.6 on 2024-08-26 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('p_no', models.IntegerField(primary_key=True, serialize=False)),
                ('places', models.CharField(default='Unknown', max_length=20)),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.DeleteModel(
            name='main',
        ),
        migrations.DeleteModel(
            name='page3',
        ),
        migrations.RemoveField(
            model_name='month',
            name='id',
        ),
        migrations.AddField(
            model_name='month',
            name='SEASON',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='page2',
            name='SEASON',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='month',
            name='M_NO',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='page2',
            name='MONTHS',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='page2',
            name='M_NO',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='month',
            table='months',
        ),
        migrations.AddField(
            model_name='place',
            name='months',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.month'),
        ),
    ]
