# Generated by Django 5.0.6 on 2024-08-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_place_delete_main_delete_page3_remove_month_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='months',
            new_name='month',
        ),
    ]
