# Generated by Django 5.0.6 on 2024-08-26 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_rename_months_place_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='registrations.month'),
        ),
    ]
