# Generated by Django 5.0.6 on 2024-08-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_alter_place_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='month',
            new_name='m_no',
        ),
    ]
