# Generated by Django 5.0.6 on 2024-08-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_rename_month_place_m_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='m_no',
            new_name='month',
        ),
    ]
