# Generated by Django 5.0.6 on 2024-08-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_rename_m_no_place_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationsMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.IntegerField()),
            ],
            options={
                'db_table'  : 'registrations_main',
            },
        ),
    ]
