# Generated by Django 5.0.6 on 2024-08-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_registrationsmain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationsMain',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='month',
            new_name='m_no',
        ),
    ]
