# Generated by Django 5.0.6 on 2024-08-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_delete_registrationsmain_rename_month_place_m_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_NO', models.IntegerField()),
                ('MONTHS', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=20)),
            ],
        ),
    ]
