# Generated by Django 5.0.6 on 2024-08-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='m_no',
            new_name='month',
        ),
        migrations.RemoveField(
            model_name='main',
            name='season',
        ),
        migrations.AddField(
            model_name='main',
            name='SEASON',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
