# Generated by Django 5.0.6 on 2024-08-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_rename_m_no_place_month_remove_main_season_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='main',
        ),
    ]
