# Generated by Django 5.0.6 on 2024-08-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_delete_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_NO', models.IntegerField()),
                ('MONTHS', models.CharField(max_length=20)),
                ('SEASON', models.CharField(default='Unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='page3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_NO', models.IntegerField()),
                ('MONTHS', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=20)),
            ],
        ),
    ]
