# Generated by Django 5.0.6 on 2024-08-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_main_page3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
