# Generated by Django 5.0.6 on 2024-08-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('P_NO', models.IntegerField(primary_key=True, serialize=False)),
                ('M_NO', models.IntegerField()),
                ('PLACES', models.CharField(default='Unknown', max_length=20)),
            ],
            options={
                'db_table': 'places',
            },
        ),
    ]
